# Generated by Django 3.0.8 on 2020-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(db_column='年级名称', max_length=15)),
                ('grade_image', models.URLField()),
                ('poetry_flag', models.IntegerField(db_column='标识', db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(db_column='分类名称', max_length=15)),
                ('mark_image', models.URLField()),
                ('poetry_flag', models.IntegerField(db_column='标识', db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('title', models.CharField(db_column='名称', max_length=15)),
                ('time', models.CharField(db_column='时间', max_length=5)),
                ('author', models.CharField(db_column='作者', max_length=10)),
                ('content', models.TextField(db_column='内容', null=True)),
                ('poetry_flag', models.IntegerField(db_column='标识', db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoetryFlag',
            fields=[
                ('poetry_type', models.CharField(db_column='类型', max_length=8)),
                ('poetry_flag', models.AutoField(db_column='标识', primary_key=True, serialize=False)),
            ],
        ),
    ]
