# Generated by Django 3.0.8 on 2020-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=15)),
                ('image', models.URLField()),
                ('author', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('desc', models.TextField(null=True)),
                ('chapters', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=15)),
                ('title', models.TextField(null=True)),
                ('paragraphs', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=15)),
                ('grade_image', models.URLField()),
                ('poetry_flag', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_name', models.CharField(max_length=15)),
                ('mark_image', models.URLField()),
                ('mark_time', models.TextField(null=True)),
                ('mark_author', models.TextField(null=True)),
                ('poetry_flag', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MergeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('desc', models.TextField(null=True)),
                ('data', models.TextField(null=True)),
                ('flag', models.CharField(default='flag', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_index', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=5)),
                ('author', models.CharField(max_length=10)),
                ('content', models.TextField(null=True)),
                ('pic', models.URLField(null=True)),
                ('poetry_flag', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoetryFlag',
            fields=[
                ('poetry_type', models.CharField(max_length=8)),
                ('poetry_flag', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
