# Generated by Django 3.0.8 on 2020-07-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradetype',
            name='grade_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='gradetype',
            name='poetry_flag',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='marktype',
            name='mark_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='marktype',
            name='poetry_flag',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='author',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='poetry_flag',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='title',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='poetryflag',
            name='poetry_flag',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poetryflag',
            name='poetry_type',
            field=models.CharField(max_length=8),
        ),
    ]
