# Generated by Django 3.0.8 on 2020-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('movieId', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=15)),
                ('image', models.TextField(null=True)),
                ('duration', models.TextField(null=True)),
                ('score', models.TextField(null=True)),
                ('mtype', models.TextField(null=True)),
                ('actor', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=10)),
                ('movie_index', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=15)),
                ('image', models.TextField(null=True)),
                ('director', models.TextField(null=True)),
                ('actor', models.TextField(null=True)),
                ('area', models.TextField(null=True)),
                ('mtime', models.TextField(null=True)),
                ('mtype', models.TextField(null=True)),
                ('score', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
