# Generated by Django 3.0.8 on 2020-09-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0002_hotmovie_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
