# Generated by Django 3.0.8 on 2020-07-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0002_auto_20200713_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poetry',
            name='index',
        ),
        migrations.AddField(
            model_name='poetry',
            name='mark_index',
            field=models.IntegerField(null=True),
        ),
    ]
