# Generated by Django 3.0.8 on 2020-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0003_auto_20200713_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='marktype',
            name='mark_author',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='marktype',
            name='mark_time',
            field=models.TextField(null=True),
        ),
    ]
