# Generated by Django 3.0.8 on 2020-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0003_movie_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectId', models.CharField(max_length=15)),
                ('title', models.TextField()),
                ('image', models.TextField()),
                ('score', models.CharField(max_length=5)),
                ('pubdateTime', models.CharField(max_length=20)),
                ('movieType', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=15)),
                ('director', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=15)),
                ('intro', models.TextField()),
                ('comments', models.TextField()),
                ('actors', models.TextField()),
                ('tags', models.TextField()),
                ('photos', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='hotmovie',
            old_name='title',
            new_name='dateId',
        ),
        migrations.RenameField(
            model_name='hotmovie',
            old_name='actor',
            new_name='movies',
        ),
        migrations.RemoveField(
            model_name='hotmovie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='hotmovie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hotmovie',
            name='movieId',
        ),
        migrations.RemoveField(
            model_name='hotmovie',
            name='mtype',
        ),
        migrations.RemoveField(
            model_name='hotmovie',
            name='score',
        ),
    ]
