# Generated by Django 3.0.8 on 2020-07-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0004_auto_20200713_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetry',
            name='pic',
            field=models.URLField(null=True),
        ),
    ]
