# Generated by Django 3.0.8 on 2020-07-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0005_poetry_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=15)),
                ('image', models.URLField()),
                ('author', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('desc', models.TextField(null=True)),
                ('chapters', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=15)),
                ('title', models.TextField(null=True)),
                ('paragraphs', models.TextField(null=True)),
            ],
        ),
    ]
