# Generated by Django 3.0.8 on 2020-07-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniprogram', '0006_book_bookchapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('data', models.TextField(null=True)),
            ],
        ),
    ]
