# 路径地址：/root/.bashrc
# 自定义环境变量
# nginx
export PATH=$PATH:/usr/local/nginx/sbin
# nodejs
export NODE_HOME=/root/app/node-v10.15.3-linux-x64
export PATH=$PATH:$NODE_HOME/bin
export NODE_PATH=$NODE_HOME/lib/node_modules
# python
export PATH=$PATH:/usr/local/python3/bin
export PATH=$PATH:/usr/local/sqlite/bin
# 语言
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
# java
export JAVA_HOME=/usr/local/jdk1.8.0_251
export JRE_HOME=${JAVA_HOME}/jre
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib
export PATH=${JAVA_HOME}/bin:$PATH
